FROM golang

WORKDIR /src
COPY go.mod /src
COPY go.sum /src

ENV GOPROXY https://goproxy.io

RUN go mod download

EXPOSE 8081

COPY . .

CMD go run ./gateway/cmd/api/gateway_api.go -f ./gateway/cmd/config/config_api.json