// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindByTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByTokenRequest) Reset()         { *m = FindByTokenRequest{} }
func (m *FindByTokenRequest) String() string { return proto.CompactTextString(m) }
func (*FindByTokenRequest) ProtoMessage()    {}
func (*FindByTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *FindByTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByTokenRequest.Unmarshal(m, b)
}
func (m *FindByTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByTokenRequest.Marshal(b, m, deterministic)
}
func (m *FindByTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByTokenRequest.Merge(m, src)
}
func (m *FindByTokenRequest) XXX_Size() int {
	return xxx_messageInfo_FindByTokenRequest.Size(m)
}
func (m *FindByTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByTokenRequest proto.InternalMessageInfo

func (m *FindByTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type FindByIdRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByIdRequest) Reset()         { *m = FindByIdRequest{} }
func (m *FindByIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindByIdRequest) ProtoMessage()    {}
func (*FindByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *FindByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByIdRequest.Unmarshal(m, b)
}
func (m *FindByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByIdRequest.Marshal(b, m, deterministic)
}
func (m *FindByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByIdRequest.Merge(m, src)
}
func (m *FindByIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindByIdRequest.Size(m)
}
func (m *FindByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByIdRequest proto.InternalMessageInfo

func (m *FindByIdRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*FindByTokenRequest)(nil), "FindByTokenRequest")
	proto.RegisterType((*FindByIdRequest)(nil), "FindByIdRequest")
	proto.RegisterType((*UserResponse)(nil), "UserResponse")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe2, 0x12, 0x72, 0xcb, 0xcc, 0x4b, 0x71, 0xaa,
	0x0c, 0xc9, 0xcf, 0x4e, 0xcd, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62,
	0x2d, 0x01, 0xf1, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x25, 0x45, 0x2e, 0x7e,
	0x88, 0x5a, 0xcf, 0x14, 0x98, 0x42, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0xb0, 0x2a, 0xe6, 0x20, 0xa6,
	0xcc, 0x14, 0xa5, 0x1c, 0x2e, 0x9e, 0xd0, 0xe2, 0xd4, 0xa2, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc,
	0xe2, 0x54, 0x74, 0x79, 0x84, 0xc1, 0x4c, 0x48, 0x06, 0x0b, 0x49, 0x71, 0x71, 0x80, 0x9c, 0x94,
	0x97, 0x98, 0x9b, 0x2a, 0xc1, 0x0c, 0x96, 0x80, 0xf3, 0x41, 0x72, 0x05, 0x89, 0xc5, 0xc5, 0xe5,
	0xf9, 0x45, 0x29, 0x12, 0x2c, 0x10, 0x39, 0x18, 0xdf, 0x28, 0x8b, 0x8b, 0x05, 0x64, 0x9b, 0x90,
	0x31, 0x17, 0x37, 0x92, 0x27, 0x84, 0x84, 0xf5, 0x30, 0xbd, 0x24, 0xc5, 0xab, 0x87, 0xec, 0x30,
	0x25, 0x06, 0x21, 0x5d, 0x2e, 0x0e, 0x98, 0x6f, 0x84, 0x04, 0xf4, 0xd0, 0x3c, 0x86, 0xa1, 0x3c,
	0x89, 0x0d, 0x1c, 0x5e, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x56, 0x26, 0x3c, 0x3d,
	0x01, 0x00, 0x00,
}
